// <auto-generated />
using Car_SharingDesktopAPP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Car_SharingDesktopAPP.Migrations.VehicleDB
{
    [DbContext(typeof(VehicleDBContext))]
    partial class VehicleDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Car_SharingDesktopAPP.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CleanStatus")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CurrentCity")
                        .HasColumnType("int");

                    b.Property<float>("FuelLevel")
                        .HasColumnType("real");

                    b.Property<int>("FuelType")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Skoda",
                            CleanStatus = 0,
                            Color = "Czarny",
                            CurrentCity = 0,
                            FuelLevel = 100f,
                            FuelType = 1,
                            IsAvailable = true,
                            Model = "Fabia",
                            RegistrationNumber = "RZ2345",
                            VehicleType = 0,
                            Year = 2015
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Seat",
                            CleanStatus = 2,
                            Color = "Czerwony",
                            CurrentCity = 0,
                            FuelLevel = 100f,
                            FuelType = 2,
                            IsAvailable = true,
                            Model = "Leon",
                            RegistrationNumber = "RZ3456",
                            VehicleType = 0,
                            Year = 2018
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
